learning_users/basic_app1/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app1 import views
import basic_app1


app_name='basic_app1'


urlpatterns = [
    
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login')
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app1 import views


urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app1/',include('basic_app1.urls')),
     path('logout/',views.user_logout,name='logout'),
]

learning_users/basic_app1/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    
    user=models.OneToOneField(User,default='user', on_delete=models.CASCADE)
    
    #additional 
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)
    
    
    def __str__(self):
        return self.user.username

learning_users/basic_app1/forms.py
from socket import fromshare
from django import forms
from django.contrib.auth.models import User
from basic_app1.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    
    
    
    class Meta():
        model=User
        fields=('username','email','password')
        


class UserPortfolioInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')        

learning_users/basic_app1/views.py
from django.shortcuts import render
from basic_app1.models import User,UserProfileInfo
from basic_app1.forms import UserForm,UserPortfolioInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request,'basic_app1/index.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    
    registred=False
    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserPortfolioInfoForm(data=request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
                user=user_form.save()
                user.set_password(user.password)
                user.save()
                
                profile=profile_form.save(commit=False)
                profile.user=user
                
                if 'profile_pic' in request.FILES:
                    profile.profile_pic=request.FILES['profile_pic']
                profile.save()
                
                registred=True
        else:
                print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserPortfolioInfoForm()            
                    
                    
    
    
    
    
    return render(request,'basic_app1/registration.html',{'user_form':user_form,'profile_form':profile_form,'registred':registred})
     
     



def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        
        user=authenticate(usernmae=username,password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print('someone tried to login and failed')
            print("username:{} and password {}".format(username,password))
            return HttpResponse("invalid login detail supplied") 
    else:
        return render(request,'basic_app1/login.html',{})       
    
    
    
    return render(request,'basic_app1/login.html')     

learning_users/templates/basic_app1/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>
    <body>


        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'index' %}">DJNAGO</a>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app1:register' %}"> Registration</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}"> Logout</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app1:login' %}"> Login</a>
                  </li>
                  {% endif %}
                     


                </ul>
              </div>
            </div>
          </nav>
       
          <div class='container'>
            {% block body_block %}


            {% endblock %}


          </div>
          
        
        <script src="" async defer></script>
    </body>
</html>

learning_users/templates/basic_app1/index.html
<!DOCTYPE html>
{% extends 'basic_app1/base.html' %}

{% block body_block %}
<h1>THis is home page</h1>

{% endblock %}

learning_users/templates/basic_app1/login.html
<!DOCTYPE html>
{% extends 'basic_app1/base.html' %}

{% block body_block %}
<h1>Please login</h1>
<form action="{% url 'basic_app1:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="ENTER USERNAME HERE">


    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" value="Login">
</form>    
{% endblock %}

learning_users/templates/basic_app1/registration.html
<!DOCTYPE html>

{% extends 'basic_app1/base.html' %}
{% load static %}

{% block body_block %}
{% if registred %}
  <h1>thank you for registraing</h1>
{% else %}
   <h1>Register here</h1>
   <h3>Fill form here<h3>
    
    <form method='post' enctype='multipart/form-data'>
        {% csrf_token %}
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <input type='submit' value='Register'>
    </form>
{% endif %}
{% endblock %}